# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNShineButton' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RNShineButton

  pod 'WCLShineButton',:git => 'https://github.com/prscX/WCLShineButton.git', :commit =>'ddd4deb'
end
